### ISSUE TITLE
keep getting NAN%

### ISSUE THREAD

**Issue by montyfert** [jneilliii/OctoPrint-BedReady#25]
hi it install fine but then i try to test reference i get 
![image](https://github.com/user-attachments/assets/296ed88b-10db-4019-abb4-6e8d8bdf8f8a)
any help would be great .
thanks
martin

**Comment by jneilliii** [comment]
this is probably related to an underlying python dependency. can you check octoprint.log for errors please.

**Comment by montyfert** [comment]
hi is this what your after
2024-09-06 13:33:34,281 - octoprint.plugins.bedready - INFO - Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
2024-09-06 13:33:51,668 - octoprint.plugins.bedready - INFO - check_bed with reference reference_2024-09-06T12:17:58.124Z.jpg (threshold 1.0)
2024-09-06 13:33:51,669 - octoprint.settings - WARNING - DeprecationWarning: Detected access to deprecated settings path ['webcam', 'snapshot'], returned value is derived from compatibility overlay. Please use the webcam system introduced with 1.9.0, this compatibility layer will be removed in a future release.
2024-09-06 13:33:51,686 - octoprint.plugins.bedready - INFO - Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
2024-09-06 13:34:12,210 - octoprint.plugins.bedready - INFO - check_bed with reference reference_2024-09-06T12:17:58.124Z.jpg (threshold 1.0)
2024-09-06 13:34:12,211 - octoprint.settings - WARNING - DeprecationWarning: Detected access to deprecated settings path ['webcam', 'snapshot'], returned value is derived from compatibility overlay. Please use the webcam system introduced with 1.9.0, this compatibility layer will be removed in a future release.
2024-09-06 13:34:12,245 - octoprint.plugins.bedready - INFO - Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
2024-09-06 13:34:22,566 - octoprint.plugins.psucontrol - INFO - Switching PSU On
2024-09-06 13:34:30,043 - octoprint.plugins.psucontrol - INFO - Switching PSU Off
2024-09-06 13:34:31,102 - octoprint.util.comm - ERROR - Unexpected error while reading from serial port
Traceback (most recent call last):

**Comment by montyfert** [comment]
and this
2024-09-06 13:32:04,915 - octoprint.plugins.bedready - INFO - check_bed with reference reference_2024-09-06T12:17:58.124Z.jpg (threshold 1.0)
2024-09-06 13:32:04,915 - octoprint.settings - WARNING - DeprecationWarning: Detected access to deprecated settings path ['webcam', 'snapshot'], returned value is derived from compatibility overlay. Please use the webcam system introduced with 1.9.0, this compatibility layer will be removed in a future release.
2024-09-06 13:33:05,714 - octoprint.plugins.bedready - INFO - check_bed with reference reference_2024-09-06T12:17:58.124Z.jpg (threshold 1.0)
2024-09-06 13:33:05,714 - octoprint.settings - WARNING - DeprecationWarning: Detected access to deprecated settings path ['webcam', 'snapshot'], returned value is derived from compatibility overlay. Please use the webcam system introduced with 1.9.0, this compatibility layer will be removed in a future release.
2024-09-06 13:33:21,274 - octoprint.plugins.excluderegion - INFO - Setting update detected: g90InfluencesExtruder=False, clearRegionsAfterPrintFinishes=False, mayShrinkRegionsWhilePrinting=True, loggingMode=octoprint, enteringExcludedRegionGcode=None, exitingExcludedRegionGcode=None, extendedExcludeGcodes={'G4': {"gcode": "G4", "mode": "exclude", "description": "Ignore all dwell commands in an excluded area to reduce delays while excluding", "type": "ExcludedGcode"}, 'M117': {"gcode": "M117", "mode": "last", "description": "Suppress display messages while excluding and output the last message encountered when exiting the excluded area", "type": "ExcludedGcode"}, 'M204': {"gcode": "M204", "mode": "merge", "description": "Record default acceleration changes while excluding and apply the most recent values in a single command after exiting the excluded area", "type": "ExcludedGcode"}, 'M205': {"gcode": "M205", "mode": "merge", "description": "Record advanced setting changes while excluding and apply the most recent values in a single command after exiting the excluded area", "type": "ExcludedGcode"}, 'M73': {"gcode": "M73", "mode": "merge", "description": "Suppress progress updates while excluding and output the most recent progress values encountered when exiting the excluded area", "type": "ExcludedGcode"}}, atCommandActions={'ExcludeRegion': [{"command": "ExcludeRegion", "parameterPattern": "^\\s*(enable|on)(\\s|$)", "action": "enable_exclusion", "description": "Default action to enable exclusion", "type": "AtCommandAction"}, {"command": "ExcludeRegion", "parameterPattern": "^\\s*(disable|off)(\\s|$)", "action": "disable_exclusion", "description": "Default action to disable exclusion", "type": "AtCommandAction"}]}
2024-09-06 13:33:23,999 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Detecting serial connection"
2024-09-06 13:33:24,043 - octoprint.util.comm - INFO - Serial detection: Performing autodetection with 1 port/baudrate candidates: /dev/ttyUSB0@115200
2024-09-06 13:33:24,044 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 115200
2024-09-06 13:33:24,046 - octoprint.util.comm - INFO - Connecting to port /dev/ttyUSB0, baudrate 115200
2024-09-06 13:33:24,076 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2024-09-06 13:33:24,107 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2024-09-06 13:33:24,125 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting serial connection" to "Operational"

**Comment by jneilliii** [comment]
Try this for starts: https://github.com/jneilliii/OctoPrint-BedReady/issues/21#issuecomment-1870441227 via SSH.

**Comment by jneilliii** [comment]
Actually, you probably need to follow this one: <https://github.com/jneilliii/OctoPrint-BedReady/issues/23#issuecomment-2087959380>.

**Comment by montyfert** [comment]
hi i tried
sudo apt install libgfortran5 libopenblas0-pthread
source ~/oprint/bin/activate
pip install numpy
deactivate
sudo service octoprint restart

and got 
libgfortran5 is already the newest version (10.2.1-6+rpi1).
libopenblas0-pthread is already the newest version (0.3.13+ds-3+rpi1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bash: /home/pi/oprint/bin/activate: No such file or directory
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.19.5)
bash: deactivate: command not found
Failed to restart octoprint.service: Unit octoprint.service not found.
pi@raspberrypi:~ $ 

not sure if it makes any difference my install was with octoprint deploy.
thanks 
martin

**Comment by jneilliii** [comment]
> bash: /home/pi/oprint/bin/activate: No such file or directory
>Failed to restart octoprint.service: Unit octoprint.service not found.

can you provide more details as to your setup? did you use octoprint_deploy or manually install on pi?

**Comment by montyfert** [comment]
i used octoprint_deploy
thanks 
martin

**Comment by jneilliii** [comment]
ok, so I think it does the venv differently. try these commands.
```
source ~/OctoPrint/venv/bin/activate
pip install numpy
```

**Comment by montyfert** [comment]
hi sorry about this but i tried that and got
bash: /home/pi/OctoPrint/venv/bin/activate: No such file or directory
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.19.5)
pi@raspberrypi:~ $

**Comment by jneilliii** [comment]
re-run octoprint deploy and from the utilities run diagnostic output and share the results, or uplaod the entire octoprint.log here for analysis to determine where your octoprint is installed to. that effects the path in the commands I've been asking you to run.

**Comment by montyfert** [comment]
sure 
[octoprint.log](https://github.com/user-attachments/files/16919208/octoprint.log)

**Comment by montyfert** [comment]
octoprint_deploy diagnostic information. Please provide ALL output for support help
**************************************
/etc/octoprint_deploy
**************************************
streamer: ustreamer
octoexec: /home/pi/OctoPrint/bin/octoprint
octopip: /home/pi/OctoPrint/bin/pip
**************************************
/etc/octoprint_instances
**************************************
instance:ender3pi port:5000 udev:true
**************************************
/etc/octoprint_cameras
**************************************
camera:cam2_ender3pi port:8002 udev:true
camera:cam_ender3pi port:8003 udev:true
**************************************
/etc/udev/rules.d/99-octoprint.rules
**************************************
KERNELS=="1-1.4:1.0",SUBSYSTEM=="tty",SYMLINK+="octo_ender3pi"
SUBSYSTEM=="video4linux", ATTRS{serial}=="12345678", ATTR{index}=="0", SYMLINK+="cam2_ender3pi"
SUBSYSTEM=="video4linux", ATTRS{serial}=="SN0001", ATTR{index}=="0", SYMLINK+="cam_ender3pi"
lrwxrwxrwx 1 root root 7 Sep  7 16:03 /dev/octo_ender3pi -> ttyUSB0
lrwxrwxrwx 1 root root 6 Sep  6 14:07 /dev/cam2_ender3pi -> video0
lrwxrwxrwx 1 root root 6 Sep  6 14:07 /dev/cam_ender3pi -> video2
**************************************
● ender3pi.service - The snappy web interface for your 3D printer
     Loaded: loaded (/etc/systemd/system/ender3pi.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-09-06 23:19:56 BST; 18h ago
   Main PID: 23216 (octoprint)
      Tasks: 56 (limit: 3933)
        CPU: 2h 34.664s
     CGroup: /system.slice/ender3pi.service
             └─23216 /home/pi/OctoPrint/bin/python3 /home/pi/OctoPrint/bin/octoprint serve --config=/home/pi/.ender3pi/config.yaml --basedir=/home/pi/.ender3pi --port=5000

Sep 07 17:46:05 raspberrypi octoprint[23216]: Error reading the file /home/pi/.ender3pi/uploads/Pen-holder-bracket-with-thread_1h15m_0.28mm_200C_PLA_ENDER3.gcode: [Errno 2] No such file or directory: '/home/pi/.ender3pi/uploads/Pen-holder-bracket-with-thread_1h15m_0.28mm_200C_PLA_ENDER3.gcode'
Sep 07 17:46:05 raspberrypi octoprint[23216]: Error reading the file /home/pi/.ender3pi/uploads/Ender_Toolholder_Fan_Mount_v2.2_45m_0.28mm_200C_PLA_ENDER3.gcode: [Errno 2] No such file or directory: '/home/pi/.ender3pi/uploads/Ender_Toolholder_Fan_Mount_v2.2_45m_0.28mm_200C_PLA_ENDER3.gcode'
Sep 07 17:46:05 raspberrypi octoprint[23216]: 2024-09-07 17:46:05,485 - octoprint.server.util.flask - WARNING - lastmodified is not timezone aware, cannot check against If-Modified-Since. In the future this will become an error!
Sep 07 17:46:06 raspberrypi octoprint[23216]: 2024-09-07 17:46:06,237 - octoprint.server.util.flask - WARNING - lastmodified is not timezone aware, cannot check against If-Modified-Since. In the future this will become an error!
Sep 07 17:46:11 raspberrypi octoprint[23216]: Error reading the file /home/pi/.ender3pi/uploads/Pen-holder-bracket-with-thread_1h15m_0.28mm_200C_PLA_ENDER3.gcode: [Errno 2] No such file or directory: '/home/pi/.ender3pi/uploads/Pen-holder-bracket-with-thread_1h15m_0.28mm_200C_PLA_ENDER3.gcode'
Sep 07 17:46:11 raspberrypi octoprint[23216]: Error reading the file /home/pi/.ender3pi/uploads/Ender_Toolholder_Fan_Mount_v2.2_45m_0.28mm_200C_PLA_ENDER3.gcode: [Errno 2] No such file or directory: '/home/pi/.ender3pi/uploads/Ender_Toolholder_Fan_Mount_v2.2_45m_0.28mm_200C_PLA_ENDER3.gcode'
Sep 07 17:46:11 raspberrypi octoprint[23216]: 2024-09-07 17:46:11,722 - octoprint.plugins.bedready - INFO - check_bed with reference reference_2024-09-06T14:01:12.808Z.jpg (threshold 0.98)
Sep 07 17:46:11 raspberrypi octoprint[23216]: 2024-09-07 17:46:11,722 - octoprint.settings - WARNING - DeprecationWarning: Detected access to deprecated settings path ['webcam', 'snapshot'], returned value is derived from compatibility overlay. Please use the webcam system introduced with 1.9.0, this compatibility layer will be removed in a future release.
Sep 07 17:46:13 raspberrypi octoprint[29764]: Lost access to message queue
Sep 07 17:46:27 raspberrypi octoprint[29824]: Lost access to message queue
None
None
{'bitrate': '10000k',
 'cleanTmpAfterDays': 7,
 'defaultWebcam': 'classic',
 'ffmpeg': None,
 'ffmpegCommandline': '{ffmpeg} -framerate {fps} -i "{input}" -vcodec '
                      '{videocodec} -threads {threads} -b:v {bitrate} -f '
                      '{containerformat} -y {filters} "{output}"',
 'ffmpegThreads': 1,
 'ffmpegThumbnailCommandline': '{ffmpeg} -sseof -1 -i "{input}" -update 1 -q:v '
                               '0.7 "{output}"',
 'ffmpegVideoCodec': 'libx264',
 'snapshotWebcam': 'classic',
 'timelapse': {'fps': 25,
               'options': {'capturePostRoll': None,
                           'interval': None,
                           'retractionZHop': None},
               'postRoll': 0,
               'type': 'off'},
 'timelapseEnabled': True,
 'watermark': True,
 'webcamEnabled': True}
**************************************
● cam2_ender3pi.service - the OctoPi(buntu) ustreamer daemon with the user specified config
     Loaded: loaded (/etc/systemd/system/cam2_ender3pi.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-09-06 14:07:42 BST; 1 day 3h ago
   Main PID: 417 (main)
      Tasks: 4 (limit: 3933)
        CPU: 7min 45.056s
     CGroup: /system.slice/cam2_ender3pi.service
             └─417 /home/pi/ustreamer/ustreamer -d /dev/cam2_ender3pi -s 0.0.0.0 -m MJPEG -r 640x480 -f 5 -p 8002 --device-timeout 8 --device-error-delay 8

Sep 06 14:49:38 raspberrypi ustreamer[417]: -- INFO  [2509.776      http] -- HTTP: NEW client (now=1): [192.168.0.71]:55241, id=6ff4b055d8bc0882
Sep 06 14:53:09 raspberrypi ustreamer[417]: -- INFO  [2720.837      http] -- HTTP: DEL client (now=0): [192.168.0.71]:55241, id=6ff4b055d8bc0882, Resource temporarily unavailable (reading,eof)
Sep 06 20:01:46 raspberrypi ustreamer[417]: -- INFO  [21237.665      http] -- HTTP: NEW client (now=1): [192.168.0.71]:64196, id=17b8390a1afb2db
Sep 06 20:01:48 raspberrypi ustreamer[417]: -- INFO  [21239.462      http] -- HTTP: DEL client (now=0): [192.168.0.71]:64196, id=17b8390a1afb2db, Resource temporarily unavailable (reading,eof)
Sep 06 21:32:56 raspberrypi ustreamer[417]: -- INFO  [26707.606      http] -- HTTP: NEW client (now=1): [192.168.0.71]:50216, id=d7f349d6ed42b4e6
Sep 06 21:51:52 raspberrypi ustreamer[417]: -- INFO  [27843.000      http] -- HTTP: DEL client (now=0): [192.168.0.71]:50216, id=d7f349d6ed42b4e6, Resource temporarily unavailable (reading,eof)
Sep 06 23:15:08 raspberrypi ustreamer[417]: -- INFO  [32839.298      http] -- HTTP: NEW client (now=1): [192.168.0.71]:52812, id=5db7861e263afa36
Sep 06 23:15:52 raspberrypi ustreamer[417]: -- INFO  [32883.296      http] -- HTTP: DEL client (now=0): [192.168.0.71]:52812, id=5db7861e263afa36, Resource temporarily unavailable (reading,eof)
Sep 07 16:03:12 raspberrypi ustreamer[417]: -- INFO  [93323.707      http] -- HTTP: NEW client (now=1): [192.168.0.71]:60243, id=3fa782c49136ce7e
Sep 07 16:10:30 raspberrypi ustreamer[417]: -- INFO  [93761.175      http] -- HTTP: DEL client (now=0): [192.168.0.71]:60243, id=3fa782c49136ce7e, Resource temporarily unavailable (reading,eof)
**************************************
● cam_ender3pi.service - the OctoPi(buntu) ustreamer daemon with the user specified config
     Loaded: loaded (/etc/systemd/system/cam_ender3pi.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-09-06 14:07:42 BST; 1 day 3h ago
   Main PID: 418 (main)
      Tasks: 4 (limit: 3933)
        CPU: 6min 40.863s
     CGroup: /system.slice/cam_ender3pi.service
             └─418 /home/pi/ustreamer/ustreamer -d /dev/cam_ender3pi -s 0.0.0.0 -m MJPEG -r 1280x720 -f 5 -p 8003 --device-timeout 8 --device-error-delay 8

Sep 07 13:41:34 raspberrypi ustreamer[418]: -- INFO  [84825.810      http] -- HTTP: NEW client (now=1): [192.168.0.71]:58758, id=4fc1112c5dcb2aab
Sep 07 13:42:04 raspberrypi ustreamer[418]: -- INFO  [84855.723      http] -- HTTP: NEW client (now=2): [192.168.0.71]:58766, id=b0bc7bbbf126890f
Sep 07 13:42:20 raspberrypi ustreamer[418]: -- INFO  [84871.512      http] -- HTTP: DEL client (now=1): [192.168.0.71]:58758, id=4fc1112c5dcb2aab, Resource temporarily unavailable (reading,eof)
Sep 07 13:42:20 raspberrypi ustreamer[418]: -- INFO  [84871.513      http] -- HTTP: DEL client (now=0): [192.168.0.71]:58766, id=b0bc7bbbf126890f, Resource temporarily unavailable (reading,eof)
Sep 07 15:16:33 raspberrypi ustreamer[418]: -- INFO  [90524.898      http] -- HTTP: NEW client (now=1): [192.168.0.71]:59229, id=a7336b01787c4c8a
Sep 07 15:25:32 raspberrypi ustreamer[418]: -- INFO  [91062.911      http] -- HTTP: DEL client (now=0): [192.168.0.71]:59229, id=a7336b01787c4c8a, Resource temporarily unavailable (reading,eof)
Sep 07 15:55:20 raspberrypi ustreamer[418]: -- INFO  [92851.641      http] -- HTTP: NEW client (now=1): [192.168.0.71]:60019, id=73a98b86329a02e1
Sep 07 15:55:52 raspberrypi ustreamer[418]: -- INFO  [92882.988      http] -- HTTP: DEL client (now=0): [192.168.0.71]:60019, id=73a98b86329a02e1, Resource temporarily unavailable (reading,eof)
Sep 07 17:46:05 raspberrypi ustreamer[418]: -- INFO  [99496.135      http] -- HTTP: NEW client (now=1): [192.168.0.71]:51185, id=163a6af6f2a986f2
Sep 07 17:46:06 raspberrypi ustreamer[418]: -- INFO  [99496.984      http] -- HTTP: NEW client (now=2): [192.168.0.71]:51187, id=583e4eafd8108dd9
**************************************
● haproxy.service - HAProxy Load Balancer
     Loaded: loaded (/lib/systemd/system/haproxy.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:haproxy(1)
             file:/usr/share/doc/haproxy/configuration.txt.gz

**Comment by jneilliii** [comment]
Try 
```
source /home/pi/OctoPrint/bin/activate
pip install --upgrade numpy
```
Note any errors and if none then. 
```
sudo service ender3pi restart
```

**Comment by montyfert** [comment]
hi i did that 
(OctoPrint) pi@raspberrypi:~ $ source /home/pi/OctoPrint/bin/activa                                                                                                         te
pip install --upgrade numpy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.o                                                                                                         rg/simple
Requirement already satisfied: numpy in ./OctoPrint/lib/python3.9/s                                                                                                         ite-packages (2.0.2)
(OctoPrint) pi@raspberrypi:~ $ sudo service ender3pi restart
(OctoPrint) pi@raspberrypi:~ $

but still getting 
![image](https://github.com/user-attachments/assets/0c59d0ad-f5d2-4708-aa2e-a58a39ee9878)
thanks 
martin

**Comment by jneilliii** [comment]
can you try this one and let me know what's returned. 
```
source /home/pi/OctoPrint/bin/activate
pip freeze | grep numpy
```

**Comment by montyfert** [comment]
pi@raspberrypi:~ $ source /home/pi/OctoPrint/bin/activate
pip freeze | grep numpy
numpy==2.0.2
(OctoPrint) pi@raspberrypi:~ $

**Comment by jneilliii** [comment]
I'm at a loss for why this is happening. I can see the error of why it's not working, but have no idea why because the version of numpy that it's loading appears to be right. 

> Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

The only thing I can think of is attempting to manually force a reinstall of numpy in the venv. 

```
source /home/pi/OctoPrint/bin/activate
pip install --force-reinstall --no-cache-dir numpy
deactivate
sudo service ender3pi restart
```

If that doesn't work basically the error above is what we have to get past.

**Comment by montyfert** [comment]
i'll give it a try 
thanks for all the help
martin

**Comment by montyfert** [comment]
hi it succeeded in reinstalling numpty, 
however its not fixed the problem , just my luck lol
martin

**Comment by mogorman** [comment]
this also didnt solve it for me journalctl shows me 
```

Dec 19 14:58:39 octopi octoprint[19192]: OpenCV bindings requires "numpy" package.
Dec 19 14:58:39 octopi octoprint[19192]: Install it via command:
Dec 19 14:58:39 octopi octoprint[19192]:     pip install numpy
```

pip says 
numpy==2.0.2 and opencv-python-headless==4.6.0.66

**Comment by jneilliii** [comment]
> pip says
> numpy==2.0.2 and opencv-python-headless==4.6.0.66

Is that pip of the os, or pip within the venv OctoPrint uses?

**Comment by mogorman** [comment]
within the venv

**Comment by mogorman** [comment]
running 
```bash
source /home/oprint/bin/activate
pip install --force-reinstall --no-cache-dir opencv-python-headless
```
i tried rebuilding opencv and still got same error

**Comment by jneilliii** [comment]
what's the python version of your venv? 

```
source /home/oprint/bin/activate
python --version
```

**Comment by mogorman** [comment]
```bash
pi@octopi:~ $ source  /home/pi/oprint/bin/activate
(oprint) pi@octopi:~ $ python --version
Python 3.9.2
```
is what it reports

**Comment by jneilliii** [comment]
Did you happen to also run `sudo apt install libopenblas0-pthread libgfortran5` @mogorman?

**Comment by jneilliii** [comment]
the previous comment covers numpy system requirements. this one will cover the opencv-headless system requirements. 

```
sudo apt install libjbig0 libxcb-render0 libtiff5 libwebp6 libsnappy1v5 libopus0 libpango-1.0-0 libdrm2 libspeex1 libva2 libfontconfig1 libharfbuzz0b libgraphite2-3 libva-drm2 libopenjp2-7 libvorbisenc2 libavformat58 libx264-155 libx265-165 libxrender1 libpangocairo-1.0-0 libthai0 libgfortran5 libpixman-1-0 libtheora0 libxfixes3 libswscale5 libxcb-shm0 libshine3 libgsm1 libswresample3 libssh-gcrypt-4 libwebpmux3 libavutil56 libdatrie1 libwavpack1 libvorbis0a libtwolame0 libva-x11-2 libgdk-pixbuf2.0-0 libsoxr0 libvpx5 libpangoft2-1.0-0 libgme0 libatlas3-base libvorbisfile3 libcroco3 libxvidcore4 libmpg123-0 libavcodec58 libaom0 libzvbi0 libmp3lame0 libcairo2 libbluray2 librsvg2-2 libchromaprint1 libogg0 libopenmpt0 libcodec2-0.8.1 libvdpau1
```

**Comment by mogorman** [comment]
after doing that i get

```
Dec 20 02:04:40 octopi octoprint[2630]: A module that was compiled using NumPy 1.x cannot be run in
Dec 20 02:04:40 octopi octoprint[2630]: NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
Dec 20 02:04:40 octopi octoprint[2630]: versions of NumPy, modules must be compiled with NumPy 2.0.
Dec 20 02:04:40 octopi octoprint[2630]: Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
Dec 20 02:04:40 octopi octoprint[2630]: If you are a user of the module, the easiest solution will be to
Dec 20 02:04:40 octopi octoprint[2630]: downgrade to 'numpy<2' or try to upgrade the affected module.
Dec 20 02:04:40 octopi octoprint[2630]: We expect that some modules will need time to support NumPy 2.
Dec 20 02:04:40 octopi octoprint[2630]: Traceback (most recent call last):  File "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
Dec 20 02:04:40 octopi octoprint[2630]:     self._bootstrap_inner()
Dec 20 02:04:40 octopi octoprint[2630]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Dec 20 02:04:40 octopi octoprint[2630]:     self.run()
Dec 20 02:04:40 octopi octoprint[2630]:   File "/usr/lib/python3.9/threading.py", line 892, in run
Dec 20 02:04:40 octopi octoprint[2630]:     self._target(*self._args, **self._kwargs)
Dec 20 02:04:40 octopi octoprint[2630]:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
Dec 20 02:04:40 octopi octoprint[2630]:     work_item.run()
Dec 20 02:04:40 octopi octoprint[2630]:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Dec 20 02:04:40 octopi octoprint[2630]:     result = self.fn(*self.args, **self.kwargs)
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
Dec 20 02:04:40 octopi octoprint[2630]:     response = self.full_dispatch_request()
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
Dec 20 02:04:40 octopi octoprint[2630]:     rv = self.dispatch_request()
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
Dec 20 02:04:40 octopi octoprint[2630]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/util/flask.py", line 1646, in decorated_view
Dec 20 02:04:40 octopi octoprint[2630]:     return func(*args, **kwargs)
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 161, in pluginCommand
Dec 20 02:04:40 octopi octoprint[2630]:     response = api_plugin.on_api_command(command, data)
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
Dec 20 02:04:40 octopi octoprint[2630]:     return f(*args, **kwargs)
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_bedready/__init__.py", line 58, in on_api_command
Dec 20 02:04:40 octopi octoprint[2630]:     result = self.check_bed(data.get("reference"), data.get("similarity"))
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_bedready/__init__.py", line 166, in check_bed
Dec 20 02:04:40 octopi octoprint[2630]:     similarity = self.compare_images(
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_bedready/__init__.py", line 124, in compare_images
Dec 20 02:04:40 octopi octoprint[2630]:     import cv2
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
Dec 20 02:04:40 octopi octoprint[2630]:     bootstrap()
Dec 20 02:04:40 octopi octoprint[2630]:   File "/home/pi/oprint/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
Dec 20 02:04:40 octopi octoprint[2630]:     native_module = importlib.import_module("cv2")
Dec 20 02:04:40 octopi octoprint[2630]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Dec 20 02:04:40 octopi octoprint[2630]:     return _bootstrap._gcd_import(name[level:], package, level)
Dec 20 02:04:40 octopi octoprint[2630]: 2024-12-20 02:04:40,614 - octoprint.cli.server - ERROR - Uncaught exception
Dec 20 02:04:40 octopi octoprint[2630]: AttributeError: _ARRAY_API not found
```

**Comment by jneilliii** [comment]
I suspect these errors are related to your previous comment `i tried rebuilding opencv and still got same error`.

**Comment by bondiblueos9** [comment]
I also am seeing this NaN behavior. Nothing in my debug logs for bedready other than INFO - check_bed followed by the DeprecationWarning from settings.  Some additional info: when I check the address of the broken image links it is http://octopi.local/plugin/bedready/images/undefined for both.

Edit: I watched octoprint.log while doing @BEDREADY after a reboot and I now have the OpenCV requires numpy message. I tried reinstalling numpy per your recommendation but it did not fix it.

Edit2: Rebooting and trying again, I then got the Numpy 1.x message. I pip install --upgrade numpy==1.26.4 from the venv, restarted octoprint, and now it is working!  I'll wait and see if I broke anything else by doing so.
